#Deduce Compiler
	SET(CMGR_COMP_MSVC 0)
	SET(CMGR_COMP_GNUCPP 0)
	SET(CMGR_COMP_CLANG 0)
	SET(CMGR_COMP_INTEL 0)
	IF(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		SET(PGT_IS_MSVC 1)
	ELSEIF(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
		SET(CMGR_COMP_GNUCPP 1)
	ELSE(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
		MESSAGE(FATAL ERROR "Your ${CMAKE_CXX_COMPILER_ID} Compiler is not specifically handled. Using Fallback.")
	ENDIF(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")

#Handle Single/Multi Config Build Systems
	SET(PGT_INTERNAL_TARGET_OUTPUT_PATH "${CMAKE_CURRENT_BINARY_DIR}")
	STRING(LENGTH ${CMAKE_CFG_INTDIR} STRLEN)
	IF(${STRLEN} LESS 2)
		#Single Config
		SET(PGT_MULTICONFIG FALSE)
		SET(CMAKE_BUILD_TYPE "build")
		SET(PGT_INTERNAL_TARGET_OUTPUT_PATH "${PGT_INTERNAL_TARGET_OUTPUT_PATH}/build")
	ELSE(${STRLEN} LESS 2)
		#Multiple Configs
		SET(PGT_MULTICONFIG TRUE)
		SET(CMAKE_BUILD_TYPE "build")
		SET(CMAKE_CONFIGURATION_TYPES "build")
	ENDIF(${STRLEN} LESS 2)

#Set Output Dir
	SET(EXECUTABLE_OUTPUT_PATH ${PGT_INTERNAL_TARGET_OUTPUT_PATH})
	SET(LIBRARY_OUTPUT_PATH ${PGT_INTERNAL_TARGET_OUTPUT_PATH})
	SET(PGT_BUILD_DIR "${CMAKE_CURRENT_BINARY_DIR}/build")

#ALL POSSIBLE CONFIGS:
	#Debug32Static
	#Debug32Dynamic
	#Release32Static
	#Release32Dynamic
	#Debug64Static
	#Debug64Dynamic
	#Release64Static
	#Release64Dynamic

#Deduce Build Options
	SET(CMGR_DEBUG 0)
	SET(CMGR_STATIC 0)
	SET(CMGR_WIN64 0)
	IF(${PGT_CONFIG} STREQUAL "Debug32Static")
		SET(CMGR_DEBUG 1)
		SET(CMGR_STATIC 1)

	ELSEIF(${PGT_CONFIG} STREQUAL "Debug32Dynamic")
		SET(CMGR_DEBUG 1)

	ELSEIF(${PGT_CONFIG} STREQUAL "Release32Static")
		SET(CMGR_STATIC 1)

	ELSEIF(${PGT_CONFIG} STREQUAL "Release32Dynamic")

	ELSEIF(${PGT_CONFIG} STREQUAL "Debug64Static")
		SET(CMGR_DEBUG 1)
		SET(CMGR_STATIC 1)
		SET(CMGR_WIN64 1)

	ELSEIF(${PGT_CONFIG} STREQUAL "Debug64Dynamic")
		SET(CMGR_DEBUG 1)
		SET(CMGR_WIN64 1)

	ELSEIF(${PGT_CONFIG} STREQUAL "Release64Static")
		SET(CMGR_STATIC 1)
		SET(CMGR_WIN64 1)

	ELSEIF(${PGT_CONFIG} STREQUAL "Release64Dynamic")
		SET(CMGR_WIN64 1)

	#NO NEW CONFIG DONT CONFUSE
	ELSE(${PGT_CONFIG} STREQUAL "Debug32Static")
		MESSAGE(FATAL_ERROR "Unsupported Configuration")
	ENDIF(${PGT_CONFIG} STREQUAL "Debug32Static")


#Set Compiler and Linker Flags
    IF(CMGR_DEBUG) 
		SET(CMAKE_CXX_FLAGS_BUILD ${CMAKE_CXX_FLAGS_DEBUG}) 
		SET(CMAKE_EXE_LINKER_FLAGS_BUILD ${CMAKE_EXE_LINKER_FLAGS_DEBUG})
	ELSE(CMGR_DEBUG)
        SET(CMAKE_CXX_FLAGS_BUILD ${CMAKE_CXX_FLAGS_RELEASE})
		SET(CMAKE_EXE_LINKER_FLAGS_BUILD ${CMAKE_EXE_LINKER_FLAGS_RELEASE})
	ENDIF(CMGR_DEBUG)

    IF(CMGR_STATIC AND CMGR_COMP_MSVC) 
		STRING(REGEX REPLACE "/MD" "/MT" ${CMAKE_EXE_LINKER_FLAGS_BUILD} TEMP)
        SET(CMAKE_EXE_LINKER_FLAGS_BUILD ${TEMP})
	ENDIF(CMGR_STATIC AND CMGR_COMP_MSVC)

#Print Information
    MESSAGE(STATUS "CMakeConfigMgr finished for ${PGT_CONFIG}")
    MESSAGE(STATUS "Specified Compiler arguments: " "${CMAKE_CXX_FLAGS_BUILD}")
    MESSAGE(STATUS "Specified Linker  arguments: " "${CMAKE_EXE_LINKER_FLAGS_BUILD}")
