#pragma once
namespace pgt {
    enum PGT_KEYS : unsigned char {
        KEY_UNKNOWN = 0,
        MBUTTON_LEFT = 1,
        MBUTTON_MIDDLE = 2,
        MBUTTON_RIGHT = 3,
        KEY_A = 'A',
        KEY_B = 'B',
        KEY_C = 'C',
        KEY_D = 'D',
        KEY_E = 'E',
        KEY_F = 'F',
        KEY_G = 'G',
        KEY_H = 'H',
        KEY_I = 'I',
        KEY_J = 'J',
        KEY_K = 'K',
        KEY_L = 'L',
        KEY_M = 'M',
        KEY_N = 'N',
        KEY_O = 'O',
        KEY_P = 'P',
        KEY_Q = 'Q',
        KEY_R = 'R',
        KEY_S = 'S',
        KEY_T = 'T',
        KEY_U = 'U',
        KEY_V = 'V',
        KEY_W = 'W',
        KEY_X = 'X',
        KEY_Y = 'Y',
        KEY_Z = 'Z',

        KEY_0 = '0',
        KEY_1 = '1',
        KEY_2 = '2',
        KEY_3 = '3',
        KEY_4 = '4',
        KEY_5 = '5',
        KEY_6 = '6',
        KEY_7 = '7',
        KEY_8 = '8',
        KEY_9 = '9',

        KEY_F1 = 201,
        KEY_F2 = 202,
        KEY_F3 = 203,
        KEY_F4 = 204,
        KEY_F5 = 205,
        KEY_F6 = 206,
        KEY_F7 = 207,
        KEY_F8 = 208,
        KEY_F9 = 209,
        KEY_F10 = 210,
        KEY_F11 = 211,
        KEY_F12 = 212,
        KEY_F13 = 213,
        KEY_F14 = 214,
        KEY_F15 = 215,
        KEY_F16 = 216,
        KEY_F17 = 217,
        KEY_F18 = 218,
        KEY_F19 = 210,
        KEY_F20 = 220,
        KEY_F21 = 221,

        KEY_CTRL_L = 221,
        KEY_CTRL_R = 222,

        KEY_ALT_L = 223,
        KEY_ALT_R = 224,

        KEY_SHIFT_L = 225,
        KEY_SHIFT_R = 226,

        KEY_UP = 227,
        KEY_DOWN = 228,
        KEY_LEFT = 229,
        KEY_RIGHT = 230,
        KEY_PLUS = 231,
        KEY_MINUS = 232,
        KEY_MULTIPLICATION = 233,
        KEY_HASH = 234,
        KEY_ENTER = 235,
        KEY_ESCAPE = 236,
        KEY_BACKSPACE = 237,
        KEY_TAB = 238,
        KEY_SPACE = ' ',

    };
}
